/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spd_mini_project;

import Backend_Files.RegisterCustomer;

/**
 *
 * @author Bala
 */
public class RegisterCustomerForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterCustomerForm
     */
    static int choice = -1;
    static boolean destroy = false;
    static String keeper_name = "";
    public RegisterCustomerForm(int choice, String name) {
        initComponents();
        this.choice = choice;
        this.keeper_name = name;
    }
    
    public RegisterCustomerForm(boolean flag, int choice, String name) {
        initComponents();
        this.choice = choice;
        this.keeper_name = name;
        this.destroy = flag;
    }
    
    RegisterCustomer register_handler = new RegisterCustomer();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        mobno = new javax.swing.JTextField();
        aadhar = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(575, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(20, 33, 61));
        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 218, 109));
        jLabel1.setText("REGISTER CUSTOMER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 280, -1));

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 218, 109));
        jLabel2.setText("Customer Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 218, 109));
        jLabel3.setText("Customer Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 218, 109));
        jLabel4.setText("Customer Mobile Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 218, 109));
        jLabel5.setText("Customer Aadhar Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        register.setBackground(new java.awt.Color(20, 33, 61));
        register.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        register.setForeground(new java.awt.Color(255, 218, 109));
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 120, -1));

        reset.setBackground(new java.awt.Color(20, 33, 61));
        reset.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 218, 109));
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 120, -1));

        name.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 166, -1));

        address.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 166, -1));

        mobno.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        getContentPane().add(mobno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 166, -1));

        aadhar.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        aadhar.setToolTipText("");
        getContentPane().add(aadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 166, -1));

        back.setBackground(new java.awt.Color(20, 33, 61));
        back.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        back.setForeground(new java.awt.Color(255, 218, 109));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 39, 80, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spd_mini_project/Banaras Supermarket - Register Form.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 260, 140));

        jLabel7.setBackground(new java.awt.Color(20, 33, 61));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        if(name.getText().length() == 0 || address.getText().length() == 0 || mobno.getText().length() == 0 || aadhar.getText().length() == 0){
            javax.swing.JOptionPane.showMessageDialog(this,"Enter all the details");
        }
        else{
            if(mobno.getText().length() != 10 || mobno.getText().matches("[0-9]+")!= true){
                javax.swing.JOptionPane.showMessageDialog(this,"Enter a valid mobile number");
                return;
            }
            if(aadhar.getText().length() != 12 || aadhar.getText().matches("[0-9]+")!= true){
                javax.swing.JOptionPane.showMessageDialog(this,"Enter a valid Aadhar number");
                return;
            }
            int result = register_handler.customer_add(aadhar.getText(), name.getText(), mobno.getText(), address.getText());
            switch (result) {
                case 0:
                    javax.swing.JOptionPane.showMessageDialog(this,"Aadhar number or mobile number already exists");
                    break;
                case 1:
                    javax.swing.JOptionPane.showMessageDialog(this,"Customer registered succesfully");
                    aadhar.setText("");
                    name.setText("");
                    mobno.setText("");
                    address.setText("");
                    this.setVisible(false);
                    try {
                            this.finalize();
                        } catch (Throwable ex) {
                            javax.swing.JOptionPane.showMessageDialog(this,"Application failure");
                        }
                    break;
                case -1:
                    javax.swing.JOptionPane.showMessageDialog(this,"Database Error");
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_registerActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        new RegisterCustomerForm(choice, keeper_name).setVisible(true);
        this.setVisible(false);
        try {
                this.finalize();
            } catch (Throwable ex) {
                javax.swing.JOptionPane.showMessageDialog(this,"Application failure");
            }
    }//GEN-LAST:event_resetActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            this.finalize();
            if(destroy == false){
                new ShopkeeperChoice(choice, keeper_name).setVisible(true);
            }
        } catch (Throwable ex) {
            javax.swing.JOptionPane.showMessageDialog(this,"Application failure");
        }
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if(choice != 2){
                    new SPD_Mini_Project().setVisible(true);
                    return;
                }
                new RegisterCustomerForm(choice, keeper_name).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhar;
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mobno;
    private javax.swing.JTextField name;
    private javax.swing.JButton register;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
