/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spd_mini_project;

/**
 *
 * @author Bala
 */
public class ShopkeeperChoice extends javax.swing.JFrame {

    /**
     * Creates new form ShopkeeperChoice
     */
    public static int choice = -1;
    public static String name = "";
    public ShopkeeperChoice(int choice, String name) {
        initComponents();
        this.choice = choice;
        this.name = name;
        jLabel1.setText("<html><pre style='font-family:Maiandra GD'>WELCOME SHOPKEEPER<center>"+name.toUpperCase()+"</center></pre><html>"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(605, 240));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 218, 109));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME SHOPKEEPER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 310, -1));

        submit.setBackground(new java.awt.Color(20, 33, 61));
        submit.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 218, 109));
        submit.setText("Continue");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        logout.setBackground(new java.awt.Color(20, 33, 61));
        logout.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 218, 109));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 120, -1));

        jRadioButton1.setBackground(new java.awt.Color(20, 33, 61));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 218, 109));
        jRadioButton1.setText("Product Billing");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(20, 33, 61));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 218, 109));
        jRadioButton2.setText("Register New Customer");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(20, 33, 61));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 218, 109));
        jRadioButton3.setText("Delete Customer or Edit Customer Details");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jRadioButton4.setBackground(new java.awt.Color(20, 33, 61));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 218, 109));
        jRadioButton4.setText("Customer Purchase History");
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spd_mini_project/Banaras Supermarket.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 260, 140));

        jLabel2.setBackground(new java.awt.Color(20, 33, 61));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected() == true){
            this.setVisible(false);
            try {
                    this.finalize();
                } catch (Throwable ex) {
                    javax.swing.JOptionPane.showMessageDialog(this,"Application failure");
                }
            new BillProductFrame(choice, name).setVisible(true);
        }
        else if(jRadioButton2.isSelected() == true){
            this.setVisible(false);
            try {
                    this.finalize();
                } catch (Throwable ex) {
                    javax.swing.JOptionPane.showMessageDialog(this,"Application failure");
                }
            new RegisterCustomerForm(false, choice, name).setVisible(true);
        }
        else if(jRadioButton3.isSelected()){
            this.setVisible(false);
            try {
                    this.finalize();
                } catch (Throwable ex) {
                    javax.swing.JOptionPane.showMessageDialog(this,"Application failure");
                }
            new EditCustomerDetailsFrame(choice, name).setVisible(true);
        }
        else if(jRadioButton4.isSelected()){
            this.setVisible(false);
            try {
                    this.finalize();
                } catch (Throwable ex) {
                    javax.swing.JOptionPane.showMessageDialog(this,"Application failure");
                }
            new PurchaseHistoryFrame(choice, name).setVisible(true);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
                this.finalize();
            } catch (Throwable ex) {
                javax.swing.JOptionPane.showMessageDialog(this,"Application failure");
            }
        new SPD_Mini_Project().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopkeeperChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopkeeperChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopkeeperChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopkeeperChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if(choice != 2){
                    new SPD_Mini_Project().setVisible(true);
                    return;
                }
                new ShopkeeperChoice(choice,name).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JButton logout;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
